import type { Metadata } from "next";
import localfont from 'next/font/local'
import "./globals.css";

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jakarta = localfont({
  src: '../assets/fonts/jakarta/PlusJakartaSans-Variable.woff2',
  display: 'swap',
  variable: '--font-jakarta',
})
 
const melodrama = localfont({
  src: '../assets/fonts/melodrama/Melodrama-Variable.woff2',
  display: 'swap',
  variable: '--font-melodrama',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">  
      <body
        className={`${jakarta.variable} ${melodrama.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
